### PR TITLE
fix steamaco meter sync process

### LINKED ISSUE #183: `SteamaCo` plugin: Broken call to `associate` Tariff on Meter sync
The Meter sync feature of the `SteamaCo` plugin calls `associate` on MPM Tariff. However, it never actually "creates" the Tariff in the database.

It's unclear whether this is 

1. User responsibility to provide the Tariffs according to Meter configuration in SteamaCo
2. A bug in the code

### PR DESCRIPTION
**Pull request by alchalade**
this MR fixes the meter synchronization process of the SteamaCo plugin.

closes #183

### CODE REVIEW

File: Website/htdocs/mpmanager/app/Services/PluginsService.php [hunk 1]
```diff
@@ -53,4 +43,12 @@ public function getByMpmPluginId($mpmPluginId)
     {
         return $this->plugin->newQuery()->where('mpm_plugin_id', $mpmPluginId)->first();
     }
+
+    public function isPluginActive(int $SPARK_METER): bool
+    {
+        return $this->plugin->newQuery()
+            ->where('mpm_plugin_id', '=', $SPARK_METER)
+            ->exists();
+    }
```
Comment (dmohns) [inline Website/htdocs/mpmanager/app/Services/PluginsService.php:52]: Can you rename the function argument? `$SPARK_METER` is misleading, as this can be called with any `plugin_id`, right?

**Review by dmohns — COMMENTED** [review]
Hey @alchalade 

looks good, thanks for the work here. Two main comments:

1. Could you check the failing CI?
2. Could you quickly explain what was the problem here? Most of this PR's changes seem like simple refactoring (which I like a lot), but that don't change the logic. Which of the changes is the actual bug fix?

Also, minor comment inside the code.

File: Website/htdocs/mpmanager/app/Services/PluginsService.php (hunk 1 above)
Comment (alchalade) [reply Website/htdocs/mpmanager/app/Services/PluginsService.php:51]: sure, the function implementation was created by the IDE based on the call from the spark meter package.

**Review by dmohns — APPROVED** [review]
:shipit:
